CREATE TABLE IF NOT EXISTS SITE_DETAILS (
    SITE_ID TEXT NOT NULL PRIMARY KEY,
    SERVICE_NAME VARCHAR(25) NOT NULL,
    SERVICE_HEALTH_CHECK_ENDPOINT VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PING_LOG (
    PING_ID TEXT PRIMARY KEY,
    HTTP_RESPONSE_STATUS INT NOT NULL,
    RESPONSE_TIME_MS INT NOT NULL,
    IS_SUCCESS BOOLEAN NOT NULL,
    SITE_ID TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (SITE_ID) REFERENCES SITE_DETAILS(SITE_ID)
);